### ISSUE TITLE
Error trying to to run the image using -ti /bin/bash

### ISSUE THREAD

**Issue by hguillermo** [aespinosa/docker-jenkins#31]
I am trying to run the image in terminal interactive mode: docker run -it and I am getting this. Any ideas?

Running from: /opt/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
May 29, 2016 8:07:51 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Logging initialized @572ms
May 29, 2016 8:07:51 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
May 29, 2016 8:07:51 PM winstone.Logger logInternal
INFO: Winstone shutdown successfully
May 29, 2016 8:07:51 PM winstone.Logger logInternal
SEVERE: Container startup failed
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.jar.JarFile.<init>(JarFile.java:154)
	at java.util.jar.JarFile.<init>(JarFile.java:118)
	at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:263)
	at winstone.HostConfiguration.<init>(HostConfiguration.java:83)
	at winstone.HostGroup.initHost(HostGroup.java:66)
	at winstone.HostGroup.<init>(HostGroup.java:45)
	at winstone.Launcher.<init>(Launcher.java:143)
	at winstone.Launcher.main(Launcher.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at Main._main(Main.java:246)
	at Main.main(Main.java:91)

**Comment by hguillermo** [comment]
I found a work around. You can run the image first and it will start correctly. Then you can attach to the process with -ti and /bin/bash. Something like this:

docker exec -i -t 665b4a1e17b6 /bin/bash

Where 665b4a1e17b6 is the container id.

**Comment by aespinosa** [comment]
That won't work because I overrode the entrypoint in https://github.com/aespinosa/docker-jenkins/blob/master/Dockerfile#L11 . In your invocatin /bin/bash is an argument to 'java -jar jenkins.war'

You have to override that again in https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime

**Comment by hguillermo** [comment]
Thanks for the info.

**Comment by maheshmadpathi** [comment]
I get the same error as @hguillermo  any clue? 

I'm trying to run Jenkins in a k8s pod with a PV, I could manually run jenkins with `docker run -ti --rm jenkins:2.129 bash` with my own image (built based on jenkins/jenkinsci) but when I try to run with a volume it fails, possibly issue with my `config.xml`?

``` bash
VM settings:
    Max. Heap Size: 3.00G
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM

Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Aug 20, 2018 2:49:38 PM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @494ms to org.eclipse.jetty.util.log.JavaUtilLog
Aug 20, 2018 2:49:39 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Aug 20, 2018 2:49:39 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath
WARNING: Empty contextPath
Aug 20, 2018 2:49:39 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.4.z-SNAPSHOT; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_171-8u171-b11-1~deb9u1-b11
Aug 20, 2018 2:49:39 PM org.eclipse.jetty.webapp.WebAppContext doStart
WARNING: Failed startup of context w.@148080bb{/,file:///var/jenkins_home/war/,UNAVAILABLE}{/var/jenkins_home/war}
java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:107)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
        at winstone.HostConfiguration$1.preConfigure(HostConfiguration.java:164)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:419)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at winstone.Launcher.<init>(Launcher.java:163)
        at winstone.Launcher.main(Launcher.java:363)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:344)
        at Main.main(Main.java:160)

Aug 20, 2018 2:49:39 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@335eadca{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Aug 20, 2018 2:49:39 PM org.eclipse.jetty.server.AbstractConnector doStop
INFO: Stopped ServerConnector@335eadca{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Aug 20, 2018 2:49:39 PM org.eclipse.jetty.server.handler.ContextHandler doStop
INFO: Stopped w.@148080bb{/,null,UNAVAILABLE}{/var/jenkins_home/war}
Aug 20, 2018 2:49:39 PM winstone.Logger logInternal
INFO: Jetty shutdown successfully
java.io.IOException: Failed to start Jetty
        at winstone.Launcher.<init>(Launcher.java:165)
        at winstone.Launcher.main(Launcher.java:363)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:344)
        at Main.main(Main.java:160)
Caused by: java.util.zip.ZipException: zip file is empty
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.getTlds(MetaInfConfiguration.java:438)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanForTlds(MetaInfConfiguration.java:355)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.scanJars(MetaInfConfiguration.java:173)
        at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:107)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
        at winstone.HostConfiguration$1.preConfigure(HostConfiguration.java:164)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:419)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at winstone.Launcher.<init>(Launcher.java:163)
        ... 7 more
```

**Comment by maheshmadpathi** [comment]
fixed the issue, few jar files got corrupted when I was migrating the storage to NFS Persistent Volume, I deleted the corrupted files and restarted Jenkins.. :boom::grey_exclamation:
